import { defineToolcraft } from "@/toolcraft/runtime";

export const appSchema = defineToolcraft({
  canvas: {
    draggable: false,
    enabled: true,
    renderScale: true,
    sizing: {
      mode: "editable-output",
    },
    upload: false,
  },
  export: {
    png: { background: "include" },
  },
  panels: {
    controls: {
      title: "Simulador",
      sections: [
        {
          title: "Capital",
          controls: {
            initialValue: {
              defaultValue: "10000",
              label: "Valor inicial",
              target: "capital.initialValue",
              type: "text",
              commitMode: "setting",
              description: "Valor inicial em reais; o painel e o canvas formatam como BRL.",
              orderRole: "primary",
              performanceRole: "responsiveness",
              performanceReason: "Recalcula uma série mensal curta e atualiza cards e gráficos.",
            },
            monthlyContribution: {
              defaultValue: "500",
              label: "Aporte mensal",
              target: "capital.monthlyContribution",
              type: "text",
              commitMode: "setting",
              description: "Aporte recorrente mensal em reais.",
              orderRole: "primary",
              performanceRole: "responsiveness",
              performanceReason: "Atualiza valores financeiros sem alterar o custo estrutural do renderer.",
            },
          },
        },
        {
          title: "Prazo",
          controls: {
            durationUnit: {
              defaultValue: "months",
              label: "Unidade",
              target: "period.durationUnit",
              type: "segmented",
              options: [
                { label: "Meses", value: "months" },
                { label: "Anos", value: "years" },
              ],
              orderRole: "mode",
              performanceRole: "responsiveness",
              performanceReason: "Altera só rótulos e leitura do prazo.",
            },
            durationMonths: {
              defaultValue: 120,
              label: "Duração",
              target: "period.durationMonths",
              type: "slider",
              min: 1,
              max: 360,
              step: 1,
              unit: "months",
              description: "Prazo interno sempre em meses; alternar anos muda apenas a leitura no canvas.",
              orderRole: "primary",
              performanceRole: "responsiveness",
              performanceReason: "Mais meses aumentam os pontos da linha e os cálculos de comparação.",
            },
          },
        },
        {
          title: "Juros",
          controls: {
            interestType: {
              defaultValue: "compound",
              label: "Tipo",
              target: "interest.type",
              type: "segmented",
              options: [
                { label: "Simples", value: "simple" },
                { label: "Composto", value: "compound" },
              ],
              orderRole: "mode",
              performanceRole: "responsiveness",
              performanceReason: "Troca fórmula de cálculo mantendo mesma série mensal.",
            },
            benchmark: {
              defaultValue: "free",
              label: "Indexador",
              target: "interest.benchmark",
              type: "select",
              options: [
                { label: "Livre", value: "free" },
                { label: "CDI", value: "cdi" },
                { label: "Selic", value: "selic" },
                { label: "IPCA+", value: "ipca" },
              ],
              orderRole: "mode",
              performanceRole: "responsiveness",
              performanceReason: "Seleciona taxa-base para a mesma fórmula de série.",
            },
            annualRate: {
              defaultValue: 12,
              label: "Taxa a.a.",
              target: "interest.annualRate",
              type: "slider",
              min: 0,
              max: 30,
              step: 0.05,
              unit: "%",
              description: "Quando Indexador é Livre, esta taxa manual define o rendimento anual; o canvas mostra a taxa mensal equivalente.",
              orderRole: "primary",
              performanceRole: "responsiveness",
              performanceReason: "Recalcula a série numérica e SVGs com custo fixo pequeno.",
            },
            benchmarkModifier: {
              defaultValue: 100,
              label: "% do índice",
              target: "interest.benchmarkModifier",
              type: "slider",
              min: 0,
              max: 150,
              step: 1,
              unit: "%",
              description: "Multiplica CDI, Selic ou IPCA+; em Livre fica como referência visual no canvas.",
              orderRole: "strength",
              performanceRole: "responsiveness",
              performanceReason: "Só altera a taxa efetiva aplicada ao cálculo.",
            },
          },
        },
        {
          title: "Impostos e Inflação",
          controls: {
            taxRate: {
              defaultValue: "15",
              label: "IR",
              target: "tax.irRate",
              type: "select",
              options: [
                { label: "22,5% até 180d", value: "22.5" },
                { label: "20% até 360d", value: "20" },
                { label: "17,5% até 720d", value: "17.5" },
                { label: "15% acima 720d", value: "15" },
              ],
              orderRole: "mode",
              performanceRole: "responsiveness",
              performanceReason: "Atualiza dedução fiscal sobre o rendimento final.",
            },
            manualTax: {
              defaultValue: false,
              label: "Manual",
              target: "tax.manualOverride",
              type: "switch",
              orderRole: "mode",
              performanceRole: "responsiveness",
              performanceReason: "Mostra ou oculta a taxa manual.",
            },
            manualTaxRate: {
              defaultValue: 15,
              label: "IR manual",
              target: "tax.manualRate",
              type: "slider",
              min: 0,
              max: 35,
              step: 0.1,
              unit: "%",
              visibleWhen: { target: "tax.manualOverride", equals: true },
              orderRole: "primary",
              performanceRole: "responsiveness",
              performanceReason: "Troca a alíquota usada na dedução líquida.",
            },
            inflation: {
              defaultValue: 4.5,
              label: "Inflação a.a.",
              target: "inflation.annualRate",
              type: "slider",
              min: 0,
              max: 20,
              step: 0.05,
              unit: "%",
              orderRole: "primary",
              performanceRole: "responsiveness",
              performanceReason: "Recalcula curva real e cards de poder de compra.",
            },
            iof: {
              defaultValue: true,
              label: "IOF",
              target: "tax.iof",
              type: "switch",
              description: "Aplicado apenas quando o prazo fica abaixo de 30 dias.",
              orderRole: "advanced",
              performanceRole: "responsiveness",
              performanceReason: "Afeta só o ajuste líquido em prazos mínimos.",
            },
          },
        },
        {
          title: "Cenários",
          controls: {
            scenarioName: {
              defaultValue: "Cenário 1",
              label: "Nome",
              target: "scenario.name",
              type: "text",
              commitMode: "content",
              orderRole: "primary",
              performanceRole: "responsiveness",
              performanceReason: "Edita apenas o nome usado ao salvar uma sobreposição.",
            },
            scenarioActions: {
              defaultValue: "idle",
              label: "Comparação",
              target: "scenario.action",
              type: "actions",
              actions: [{ label: "Comparar Cenários", value: "save-scenario" }],
              orderRole: "action",
              performanceRole: "responsiveness",
              performanceReason: "Salva até três configurações para sobrepor nos gráficos.",
            },
          },
        },
        {
          title: "Background",
          controls: {
            includeBackground: {
              defaultValue: true,
              label: "Include",
              target: "export.includeBackground",
              type: "switch",
              orderRole: "primary",
              performanceRole: "responsiveness",
              performanceReason: "Controla fundo do preview e transparência do PNG.",
            },
            background: {
              defaultValue: { hex: "#08110d" },
              label: false,
              target: "appearance.background",
              type: "color",
              orderRole: "color",
              performanceRole: "responsiveness",
              performanceReason: "Altera só a cor de fundo do dashboard/exportação.",
            },
          },
          layoutGroups: [{ layout: "inline", columns: 2, controls: ["includeBackground", "background"] }],
        },
        {
          title: "Image Export",
          controls: {
            imageFormat: {
              defaultValue: "png",
              label: "Format",
              target: "export.image.format",
              type: "select",
              options: [
                { label: "PNG", value: "png" },
                { label: "JPG", value: "jpg" },
              ],
              orderRole: "mode",
              performanceRole: "responsiveness",
              performanceReason: "Seleciona o tipo de arquivo entregue pelo export.",
            },
            imageResolution: {
              defaultValue: "4k",
              label: "Resolution",
              target: "export.image.resolution",
              type: "select",
              options: [
                { label: "2K", value: "2k" },
                { label: "4K", value: "4k" },
                { label: "8K", value: "8k" },
              ],
              orderRole: "primary",
              performanceRole: "workload",
              performanceReason: "Aumenta a dimensão real do PNG exportado.",
            },
          },
          layoutGroups: [{ layout: "inline", columns: 2, controls: ["imageFormat", "imageResolution"] }],
        },
        {
          title: "Export",
          controls: {
            exportActions: {
              defaultValue: "idle",
              target: "export.actions",
              type: "panelActions",
              actions: [{ label: "Exportar", value: "export-png", icon: "upload-simple", variant: "default" }],
            },
          },
        },
      ],
    },
  },
  persistence: {
    storage: "localStorage",
    key: "toolcraft:compound-interest-simulator:state:v1",
    version: 1,
    include: ["values", "canvas", "panels"],
  },
  settingsTransfer: { enabled: true, appId: "compound-interest-simulator", fileName: "simulador-juros-settings.json" },
  toolbar: {
    history: true,
    radar: true,
    theme: true,
    zoom: true,
  },
});
